# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: api-gateway
service:
  name: api-gateway-svc
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32023

deployment:
  name: api-gateway
  replicaCount: 1
  image:
    repository: camsagaz/api-gateway
    version: v0.1.4
