# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: account-service
service:
  name: account-service-svc
  type: ClusterIP
  port: 80
  targetPort: 80

deployment:
  name: account-service
  replicaCount: 1
  image:
    repository: camsagaz/account-service
    version: v0.1.6
    pullPolicy: Always
  env:
    rabbitHost: rabbitmq.messaging.svc.cluster.local
    mongoHost: mongodb.database.svc.cluster.local
    mongoDatabase: K8SDEMO
    mongoCollection: USERS

ingress:
  name: account-service-ingress
  hostName: account.service.com
  port: 80

secrets: #This is just a prove of concept to manage secrets in the easiest way.
  name: account-service-secret
  username: admin
  password: admin_pass
