apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  app: {{ .Values.app }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      annotations:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.version}}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP