apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ .Values.app }}
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc }}
  password: {{ .Values.secrets.password | b64enc }}
